-- UUIDs are now generated by Hibernate (UUIDv7, time-ordered) instead of
-- PostgreSQL's gen_random_uuid() (UUIDv4, random). This improves B-tree
-- index locality for inserts.

ALTER TABLE manga ALTER COLUMN id DROP DEFAULT;
ALTER TABLE notification_log ALTER COLUMN id DROP DEFAULT;
